language: java
jdk:
- openjdk8
install: true
script:
- chmod u+x gradlew
- "./gradlew test build distTar"
deploy:
  provider: releases
  skip_cleanup: true
  file: build/distributions/clusterize.tar
  on:
    tags: true
  api_key:
    secure: IxDLSH3eou5tQPKunboKwt4ANBVAzEe/JSUPvznSxcFLG2WA6FJKehoVNNWecWpnIy70FhLTYf54KgucBGRlLu2RV5nSC1jCVlmxu8FyhnASc5+FTS9tdh2Dbq0WyIh+1CW7NnufQ0rmKdTBEzhL+bLtE2gZ3sNS8P7rH5KncRTXcQb+XN6sa1lGtNc2ldQuwT1QbxjoKjcQLjMzd/UKtp7M7SVUXIzUfrEgaQvgkTcdqOLjAtRR5tr6Qq1f+0Wc1p+KZwWFICgjG1+SKqVfuf8cob6J2h34RnWFb4B1GdADiVbEOa9EhIATKo87V5NYsJgZsWHxo2JE4ZM3dpfnuZz1k/T0muw9QayL5798h6RH++niFIexgbVqWjrpMu4wPCdb/aetSGSdeegekzFRiCns3yLZUn+wdQZwsyYve6tdZKg5ARCNN2P6vITJmWFOD/RYQxQfjFLg4ET/kA5HIN/DB4RRff34EwIXnyFVLebSDtn7glkx87J3BcfGsEiH2zQgBlqJqn85qDV2tfRjQ5Aq2Xj26F5ci+6uR+Q5hNWNHJFazGy1iXw+BVlHFFTsmdVQ49YVpeBHCe5uwXvlWY6RVUfufUXiMOOAXRnbi8D8s7Xtw1oUZZrA7bMh7xXzX4P+VyUrVSpgBkrX5hsfYdiK28HtmzImiJ2yMpewcfI=
