# defines iterations in given order
iterations:
  - type: ARRAY # will iterate over values given in array
    name: VICINITY_TYPE
    values: [10]

  - type: INT_RANGE # will iterate over given integer range
    name: MIN_TRANSL
    from: 1
    to: 1
    step: 1
    stepOperation: PLUS

  - type: ARRAY
    name: ADDED_LAYERS
    values: ['[10, 20, 30]', '[20, 20]']

  - type: INT_RANGE
    name: SUB_IMG_IDX
    from: 1
    to: 1
    step: 1
    stepOperation: PLUS

  - type: INT_RANGE
    name: RUN_ID
    from: 1
    to: 1
    step: 1
    stepOperation: PLUS

general:
  #  metadataStoragePath: 'dockershared/metadataStorage'
  storagePath: 'dockershared/storage' #usually storage
  sourcesPath: './src/test/resources/sources'
  maxResubmits: 1
  variables:
  dependents:
    - name: MAX_TRANSL
      dependentVarName: VICINITY_TYPE
      modifier: '+1'

taskType:
  type: MATLAB # type of runner
  functionCall: |
    main_batch01($MIN_TRANSL, $MAX_TRANSL, $VICINITY_TYPE, $SUB_IMG_IDX, 'useGPU', 'yes', 'layers', $ADDED_LAYERS)

resources:
  profile: 'CUSTOM'
  toolboxes:
    - matlab_Neural_Network_Toolbox
  modules:
    - jdk-8