# defines iterations in given order
iterations:
  - type: INT_RANGE
    name: FIB_TO
    from: 1
    to: 41
    step: 1
    stepOperation: PLUS

general:
  #  metadataStoragePath: 'dockershared/metadataStorage'
  storagePath: 'dockershared/storage' #usually storage
  sourcesPath: 'dockershared/sources'
  maxResubmits: 3
  variables:
  dependentVariables:
    - name: MAX_TRANSL
      dependentVarName: VICINITY_TYPE
      modifier: '+1'

taskType:
  type: PYTHON # type of runner
  command: |-
    from python_fibonacci import main; main(1, $FIB_TO)

resources:
  profile: 'AUTO'
  resourceType: 'CPU'