# defines iterations in given order
iterations:
  - type: INT_RANGE
    name: FROM
    from: 1
    to: 2
    step: 1
    stepOperation: PLUS

general:
  #  metadataStoragePath: 'customer_metadata_storage_path'
  storagePath: 'out-python'
  sourcesPath: 'sources'
  maxResubmits: 5
taskType:
  type: PYTHON # type of runner
  command: |-
    python python_file.py
resources:
  profile: 'CUSTOM'
  resourceType: 'CPU'