# defines iterations in given order
iterations:
  - type: INT_RANGE
    name: X
    from: 1
    to: 5
    step: 1
    stepOperation: PLUS
  - type: INT_RANGE
    name: Y
    from: 1
    to: 5
    step: 1
    stepOperation: PLUS

general:
  #  metadataStoragePath: 'customer_metadata_storage_path'
  #  storagePath: 'custom_storage_path'
  sourcesPath: 'sources'
  maxResubmits: 3
  dependentVariables:
    - name: MAX_TRANSL
      dependentVarName: Y
      modifier: '+15'
taskType:
  type: PYTHON # type of runner
  command: |-
    python -c "from python_fibonacci import main; main($Y, $X)"
resources:
  profile: 'CUSTOM'
  resourceType: 'CPU'