# defines iterations in given order
iterations:
  - type: INT_RANGE
    name: X
    from: 1
    to: 4
    step: 1
    stepOperation: PLUS
  - type: INT_RANGE
    name: Y
    from: 5
    to: 8
    step: 1
    stepOperation: PLUS

general:
  #  metadataStoragePath: 'customer_metadata_storage_path'
  storagePath: 'out-python'
  sourcesPath: 'sources'
  maxResubmits: 3
taskType:
  type: PYTHON # type of runner
  command: |-
    python -c "from python_fibonacci import main; main($Y, $X)"
resources:
  profile: 'CUSTOM'
  resourceType: 'CPU'